[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
market_state = "DcqNBKGGXjaLXGftVsxXUrpePY9GU65UcDiPikDUtH35"
vault = "9BFXopHo6M4VRoLaGwdnt1Ht1Y7EMzY6rW3H8PbKpjoB"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha tests/**/*.test.cjs"

[hooks]
