[toolchain]
anchor_version = "1.1.2"

[features]
resolution = true
skip-lint = true

[programs.localnet]
market_state = "5nHB2F1c5fzXiiUwpQqY6RT6nXfboQfMGiBnMSkCAJc9"
vault = "AB41HEqA7PfEbysT5c9DX7A9MNa65GDpG397CoN5cj3z"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha tests/**/*.test.cjs"

[hooks]
